//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageApp.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        public long ID_пользователя { get; set; }
        public string Почта { get; set; }
        public string Пароль { get; set; }
        public long ID_роли { get; set; }
    
        public virtual Роли Роли { get; set; }
    }
}
